#!/usr/bin/env python3
import sys

for line in sys.stdin:
    roll, dept, marks = line.strip().split(",")
    print(dept + "\t" + marks)



#!/usr/bin/env python3
import sys

current = None
total = 0
count = 0

for line in sys.stdin:
    line = line.strip()
    dept, marks = line.split("\t")
    marks = float(marks)

    if dept == current:
        total += marks
        count += 1
    else:
        if current is not None:
            print(current + "\t" + str(total / count))
        current = dept
        total = marks
        count = 1

if current is not None:
    print(current + "\t" + str(total / count))
